development:
  adapter: postgresql
  encoding: unicode
  database: customer_care
  pool: 5
  username: hamzaaltaf
  timeout: 5000
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: customer_care_test
  pool: 5
  username: hamzaaltaf
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: customer_care
  pool: 5
  username: hamzaaltaf
  timeout: 5000